import { test, expect } from '@playwright/test'

test('свайп раскрывает сохраненный экран, отмена и повторный возврат без перезагрузки', async ({ page, context }) => {
  await context.addInitScript(() => {
    Object.defineProperty(navigator, 'onLine', { get: () => false })
    Object.defineProperty(navigator, 'userAgent', { get: () => 'iPhone' })
    Object.defineProperty(navigator, 'standalone', { get: () => true })
  })
  await context.route(/supabase\.co/, route => route.abort())
  await page.goto('/kachalka-app/')
  const user = await page.evaluate(async () => (await import('/kachalka-app/src/test/e2eSeed.js')).seedE2E())
  await page.reload()
  await page.getByRole('button', { name: user.name }).click()
  for (const digit of user.pin) await page.locator('.keypad .key', { hasText: new RegExp(`^${digit}$`) }).click()
  await page.getByRole('button', { name: 'Открыть профиль' }).click()
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  const settings = page.locator('.settings-screen')
  await expect(settings).toBeVisible()
  // Пометка DOM-экземпляра доказывает, что это прежний экран, а не повторный рендер с загрузкой.
  await settings.evaluate(el => { el.dataset.retained = 'yes' })
  await page.getByRole('button', { name: /Оформление/ }).click()
  const content = page.locator('.content')
  const start = async (x = 185) => {
    await content.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: 10, clientY: 230 }] })
    await content.dispatchEvent('touchmove', { touches: [{ identifier: 1, clientX: x, clientY: 230 }] })
  }
  await start()
  const underlay = page.locator('.content > .nav-stack > .nav-underlay')
  await expect(underlay).toBeVisible()
  await expect(settings).toHaveAttribute('data-retained', 'yes')
  await expect(underlay).toHaveAttribute('inert', '')
  const left = await page.locator('.content > .nav-stack > .nav-current').evaluate(el => el.getBoundingClientRect().left)
  expect(left).toBeGreaterThan(150)
  expect(await page.locator('.tabbar').evaluate(el => {
    const r = el.getBoundingClientRect()
    return el.contains(document.elementFromPoint(r.right - 20, r.top + 25))
  })).toBe(true)
  await page.screenshot({ path: 'test-results/swipe-midpoint.png' })
  await content.dispatchEvent('touchcancel', { touches: [] })
  await expect(underlay).toBeHidden()
  await expect(page.getByRole('heading', { name: 'Оформление' })).toBeVisible()
  await start(260)
  await content.dispatchEvent('touchend', { touches: [] })
  await expect(settings).toBeVisible()
  await expect(settings).toHaveAttribute('data-retained', 'yes')
  await expect(page.locator('.content > .nav-stack > .nav-current')).toHaveAttribute('data-route', 'profile')
  await expect(page.locator('.content [data-swiping]')).toHaveCount(0)
  // Вложенный локальный экран Настроек использует тот же механизм.
  await start(200)
  await expect(page.locator('.profile-stack > .nav-underlay')).toBeVisible()
  await content.dispatchEvent('touchend', { touches: [] })
  await expect(page.getByRole('button', { name: 'Настройки', exact: true })).toBeVisible()
  await expect(settings).toHaveCount(0)
  await page.screenshot({ path: 'test-results/swipe-return.png' })
})
